# Generated by Django 5.1.2 on 2025-01-31 11:47

import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                default="default-profile-pic.jpg",
                upload_to=journal.models.profile_pic_upload_path,
                verbose_name="profile picture",
            ),
        ),
    ]
