# Generated by Django 5.0.1 on 2024-03-17 08:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EditTag",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="comment",
            name="entry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="journal.journalentry",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 17, 19, 53, 22, 842444)
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateField(default=datetime.date(2024, 3, 18), null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 17, 19, 53, 22, 842444)
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 17, 19, 53, 22, 847420)
            ),
        ),
        migrations.DeleteModel(
            name="JournalEntryTag",
        ),
    ]
