# Generated by Django 5.2.4 on 2025-07-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="ai_generation_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="insight_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="topic_check_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="topic_check_passed",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
