# Generated by Django 5.0.1 on 2024-08-03 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="last_reset_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 3, 16, 58, 26, 280793)
            ),
        ),
    ]
