# Generated by Django 5.1.2 on 2025-02-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="penalty",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="reward",
        ),
        migrations.AddField(
            model_name="habit",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Easy Peasy 💖"),
                    ("moderate", "Glamorous Effort ✨"),
                    ("hard", "Ultimate Sissy Challenge 💪"),
                ],
                default="moderate",
                max_length=20,
            ),
        ),
    ]
