# Generated by Django 5.2.4 on 2025-07-28 09:21

import fernet_fields.fields
import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_journalentry_ai_generation_error_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="ai_generation_error",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="insight_generated_at",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="topic_check_at",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="topic_check_passed",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="is_on_topic",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                default=journal.models.get_current_timestamp, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="content",
            field=fernet_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="insight",
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="prompt_text",
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="timestamp",
            field=models.DateTimeField(default=journal.models.get_current_timestamp),
        ),
    ]
