# Generated by Django 5.0.1 on 2024-08-03 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_alter_habit_last_reset_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 3, 19, 44, 7, 593111)
            ),
        ),
    ]
