# Generated by Django 4.2.4 on 2023-09-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0003_alter_journalentry_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                default="default.jpg", upload_to="media/profile_pics"
            ),
        ),
    ]
