# Generated by Django 5.1.2 on 2025-02-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_remove_habit_penalty_remove_habit_reward_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="collective_insight",
        ),
    ]
