# Generated by Django 4.2.4 on 2023-09-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0004_alter_customuser_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="polarity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="sentiment",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="subjectivity",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
