# Generated by Django 4.2.4 on 2023-09-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0005_journalentry_polarity_journalentry_prompt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="sentiment",
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
