# Generated by Django 4.2.4 on 2023-09-11 03:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0007_alter_journalentry_sentiment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="prompt",
        ),
    ]
