# Generated by Django 4.2.4 on 2023-09-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0009_journalentry_insight"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="insight1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="insight2",
            field=models.TextField(blank=True, null=True),
        ),
    ]
