# Generated by Django 5.0.1 on 2024-10-09 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0010_alter_habit_last_reset_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 10, 0, 4, 0, 128034)
            ),
        ),
    ]
