# Generated by Django 5.0.1 on 2024-08-05 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0010_remove_customuser_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 5, 18, 15, 57, 931734)
            ),
        ),
    ]
