# Generated by Django 5.0.1 on 2024-07-21 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0011_alter_habit_timestamp_alter_userfeedback_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="habit",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 21, 10, 23, 51, 7081)
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 21, 10, 23, 51, 41107)
            ),
        ),
    ]
