# Generated by Django 5.0.1 on 2024-08-05 22:31

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0011_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="activate_account_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 6, 8, 31, 40, 385971)
            ),
        ),
    ]
