# Generated by Django 5.0.1 on 2024-08-06 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0012_alter_customuser_activate_account_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="activate_account_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 6, 14, 25, 16, 769400)
            ),
        ),
    ]
