# Generated by Django 5.0.1 on 2024-08-06 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0013_alter_customuser_activate_account_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_superuser",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="activate_account_token",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="sissy_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 6, 21, 12, 12, 726313)
            ),
        ),
    ]
