# Generated by Django 5.0.1 on 2024-08-06 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0014_remove_customuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 6, 21, 50, 10, 265799)
            ),
        ),
    ]
