# Generated by Django 5.0.1 on 2024-07-23 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0014_alter_habit_timestamp_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="progress",
            new_name="count",
        ),
        migrations.AlterField(
            model_name="habit",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 23, 11, 12, 14, 666503)
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 23, 11, 12, 14, 666503)
            ),
        ),
    ]
