# Generated by Django 5.0.1 on 2024-08-06 13:51

import datetime
import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0015_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                default=journal.models.current_timestamp, editable=False
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 6, 23, 51, 41, 236743)
            ),
        ),
    ]
