# Generated by Django 5.0.1 on 2024-08-06 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0016_customuser_date_joined_customuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 7, 1, 52, 56, 598779)
            ),
        ),
    ]
