# Generated by Django 5.0.1 on 2024-10-11 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0017_habit_longest_streak_days_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 12, 4, 0, 42, 401781)
            ),
        ),
    ]
