# Generated by Django 5.0.1 on 2024-08-07 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0020_alter_customuser_activate_account_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 7, 17, 56, 13, 906842)
            ),
        ),
    ]
