# Generated by Django 5.0.1 on 2024-07-25 10:29

import datetime
import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0021_alter_habit_timestamp_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="points",
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(
                default=journal.models.current_timestamp, verbose_name="date joined"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 25, 20, 29, 39, 952382)
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 25, 20, 29, 39, 957382)
            ),
        ),
    ]
