# Generated by Django 5.0.1 on 2024-07-25 14:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0022_remove_userprofile_points_customuser_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sticker", "Digital Sticker"),
                    ("unlock_content", "Unlock New Content"),
                    ("sissy_store_credit", "Sissy Store Credit"),
                    ("new_outfit", "New Outfit"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 26, 0, 58, 31, 321033)
            ),
        ),
        migrations.AlterField(
            model_name="taskcompletion",
            name="journal_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="journal.journalentry"
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="reward",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sticker", "Digital Sticker"),
                    ("unlock_content", "Unlock New Content"),
                    ("sissy_store_credit", "Sissy Store Credit"),
                    ("new_outfit", "New Outfit"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 26, 0, 58, 31, 327017)
            ),
        ),
    ]
