# Generated by Django 5.0.1 on 2024-07-25 23:46

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0023_alter_habit_reward_alter_habit_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_reset_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="habit",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="habit",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 26, 9, 46, 19, 675375)
            ),
        ),
    ]
