# Generated by Django 5.0.1 on 2024-08-07 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0023_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_moderator",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 7, 23, 53, 19, 803975)
            ),
        ),
    ]
