# Generated by Django 5.0.1 on 2024-10-11 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0024_rename_author_comment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 12, 8, 53, 57, 709463)
            ),
        ),
    ]
