# Generated by Django 5.0.1 on 2024-10-14 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0026_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="category",
            field=models.CharField(
                choices=[
                    ("fashion", "Fashion"),
                    ("beauty", "Beauty"),
                    ("health", "Health"),
                    ("fitness", "Fitness"),
                    ("lifestyle", "Lifestyle"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 14, 15, 22, 55, 32526)
            ),
        ),
    ]
