# Generated by Django 5.0.1 on 2024-08-08 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0028_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="author",
            field=models.CharField(default="Sissy Sparkles", max_length=100),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 8, 12, 9, 5, 500095)
            ),
        ),
    ]
