# Generated by Django 5.0.1 on 2024-08-08 03:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("journal", "0029_alter_blogpost_author_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="entry",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="thread",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="title",
        ),
        migrations.AlterField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 8, 13, 2, 16, 727640)
            ),
        ),
    ]
