# Generated by Django 5.0.1 on 2024-08-08 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0030_rename_author_comment_user_remove_comment_entry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 9, 0, 36, 58, 636744)
            ),
        ),
    ]
