# Generated by Django 5.0.1 on 2024-11-03 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0032_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="sissy_name",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="task",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 3, 20, 41, 10, 88001)
            ),
        ),
    ]
