# Generated by Django 5.0.1 on 2024-11-04 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0034_alter_userfeedback_timestamp_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 5, 7, 1, 18, 910325)
            ),
        ),
    ]
