# Generated by Django 5.0.1 on 2024-08-09 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0035_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="subscription_type",
        ),
        migrations.AddField(
            model_name="billing",
            name="subscription_tier",
            field=models.CharField(default="free", max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_subscriber",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 9, 23, 57, 28, 257829)
            ),
        ),
    ]
