# Generated by Django 5.0.1 on 2024-08-10 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0037_rename_user_question_author_answer_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 11, 7, 22, 49, 663642)
            ),
        ),
    ]
