# Generated by Django 5.0.1 on 2024-08-10 21:30

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0038_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 11, 7, 30, 18, 434925)
            ),
        ),
    ]
