# Generated by Django 5.0.1 on 2024-08-11 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0040_alter_billing_is_active_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 11, 16, 15, 30, 725904)
            ),
        ),
    ]
