# Generated by Django 5.0.1 on 2024-11-13 00:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0045_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="points",
            new_name="points_awarded",
        ),
        migrations.RemoveField(
            model_name="task",
            name="completed_by",
        ),
        migrations.RemoveField(
            model_name="task",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="task",
            name="title",
        ),
        migrations.RemoveField(
            model_name="task",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="points_penalty",
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name="task",
            name="task_id",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="task",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 13, 11, 8, 37, 543123)
            ),
        ),
    ]
