# Generated by Django 5.0.1 on 2024-08-15 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0045_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 15, 16, 29, 43, 352609)
            ),
        ),
    ]
