# Generated by Django 5.0.1 on 2024-11-13 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0046_rename_points_task_points_awarded_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 13, 11, 30, 57, 699144)
            ),
        ),
    ]
