# Generated by Django 5.0.1 on 2024-09-28 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0049_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 29, 8, 9, 40, 139662)
            ),
        ),
    ]
