# Generated by Django 5.0.1 on 2024-11-14 20:45

import django.utils.timezone
import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0049_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                default="default.jpg",
                upload_to=journal.models.profile_pic_upload_path,
                verbose_name="profile picture",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
