# Generated by Django 5.0.1 on 2024-11-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0050_alter_customuser_profile_picture_alter_post_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
