# Generated by Django 5.0.1 on 2024-09-30 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0051_alter_activitylog_user_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activitylog",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "User logged in"),
                    ("LOGOUT", "User logged out"),
                    ("PROFILE_UPDATE", "User updated profile"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 30, 11, 50, 43, 977994)
            ),
        ),
    ]
