# Generated by Django 5.0.1 on 2024-11-15 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0051_journalentry_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="id",
        ),
        migrations.AlterField(
            model_name="task",
            name="task_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
