# Generated by Django 5.0.1 on 2024-09-30 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0052_activitylog_end_date_activitylog_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 10, 1, 6, 17, 21, 593500)
            ),
        ),
    ]
