# Generated by Django 5.0.1 on 2024-11-21 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0054_rename_last_reset_date_habit_last_reset_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="last_reset",
            new_name="last_reset_date",
        ),
    ]
