# Generated by Django 5.0.1 on 2024-11-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0055_rename_last_reset_habit_last_reset_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
