# Generated by Django 5.0.1 on 2024-11-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0056_alter_resourcecategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='allow_comments',
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
