# Generated by Django 5.0.1 on 2024-11-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0057_remove_resource_allow_comments_alter_resource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
