# Generated by Django 5.1.3 on 2024-12-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0061_remove_customuser_is_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
