# Generated by Django 5.1.3 on 2024-12-01 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0062_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_body',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_bottom',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_hair',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_shoes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar_top',
        ),
    ]