# Generated by Django 5.1.3 on 2024-12-02 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
       ('journal', '0063_remove_customuser_avatar_body_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
