# Generated by Django 5.1.3 on 2024-12-10 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0008_alter_avatar_hair_color_alter_avatar_user'),
        ('journal', '0064_delete_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sissy', to='dressup.avatar'),
        ),
    ]
