# Generated by Django 5.1.3 on 2024-12-24 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0016_alter_purchaseditem_unique_together'),
        ('journal', '0066_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sissy_avatar', to='dressup.avatar'),
        ),
    ]
