# Generated by Django 5.1.3 on 2024-12-28 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0016_alter_purchaseditem_unique_together'),
        ('journal', '0067_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_avatar', to='dressup.avatar'),
        ),
    ]
