# Generated by Django 5.0.1 on 2024-06-14 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0081_alter_habit_timestamp_alter_todo_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="reward_issued",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="collective_insight",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="collective insight",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 14, 19, 37, 30, 268775)
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateField(default=datetime.date(2024, 6, 15), null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 14, 19, 37, 30, 268775)
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 14, 19, 37, 30, 273774)
            ),
        ),
    ]
