# Generated by Django 5.0.1 on 2024-06-23 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "journal",
            "0093_remove_journalentry_prompt_journalentry_prompt_text_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 23, 15, 41, 23, 255987)
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 23, 15, 41, 23, 257012)
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 23, 15, 41, 23, 263400)
            ),
        ),
    ]
