# Generated by Django 5.0.1 on 2024-06-29 16:02

import datetime
import journal.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0112_alter_habit_timestamp_alter_todo_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="locked_content",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="customuser",
            name="points",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="habit",
            name="category",
            field=models.CharField(
                choices=[
                    ("fashion_goals", "Fashion Goals"),
                    ("behavioral_goals", "Behavioral Goals"),
                    ("sissification_tasks", "Sissification Tasks"),
                    ("performance_tasks", "Performance Tasks"),
                    ("chastity_goals", "Chastity Goals"),
                    ("self_care", "Self care"),
                    ("domme_appreciation", "Domme Appreciation"),
                    ("orders", "Orders"),
                ],
                default="sissification_tasks",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="penalty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reminder", "Reminder Message"),
                    ("lock_content", "Lock Content"),
                    ("50_lines", "Write 50 lines"),
                    ("corner_time", "15 minutes Corner Time"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 30, 2, 2, 52, 558433)
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="due_date",
            field=models.DateField(default=journal.models.default_due_date, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="penalty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("reminder", "Reminder Message"),
                    ("lock_content", "Lock Content"),
                    ("50_lines", "Write 50 lines"),
                    ("corner_time", "15 minutes Corner Time"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="timestamp",
            field=models.DateTimeField(default=journal.models.current_timestamp),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 6, 30, 2, 2, 52, 558433)
            ),
        ),
    ]
