# Generated by Django 5.0.1 on 2024-06-30 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0113_customuser_locked_content_customuser_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="category",
            field=models.CharField(
                choices=[
                    ("Domme", "Domme Task"),
                    ("Sissy", "Sissy Task"),
                    ("Punishment", "Punishment Task"),
                    ("work", "Work/Study Task"),
                    ("self_care", "Self Care Task"),
                    ("chore", "Chore Task"),
                    ("personal", "Personal Task"),
                ],
                default="personal",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="priority",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="habit",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 1, 6, 0, 5, 473937)
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 1, 6, 0, 5, 484254)
            ),
        ),
    ]
