# Generated by Django 5.0.1 on 2024-07-01 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0114_todo_category_todo_priority_alter_habit_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 1, 14, 52, 51, 612189)
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 1, 14, 52, 51, 627848)
            ),
        ),
    ]
