# Generated by Django 5.0.1 on 2024-07-03 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0118_alter_habit_timestamp_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="badges",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="customuser",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="habit",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 3, 12, 16, 43, 178373)
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 3, 12, 16, 43, 178373)
            ),
        ),
    ]
