# Generated by Django 5.0.1 on 2024-07-04 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0123_alter_habit_timestamp_alter_userfeedback_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar_body",
            field=models.CharField(
                default="/static/virtual_try_on/avatars/body/light/hourglass.png",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar_bottom",
            field=models.CharField(
                default="/static/virtual_try_on/garmets/skirts/1.png", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar_hair",
            field=models.CharField(
                default="/static/virtual_try_on/avatars/hair/long_straight/blonde.png",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar_shoes",
            field=models.CharField(
                default="/static/virtual_try_on/garmets/shoes/1.png", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="avatar_top",
            field=models.CharField(
                default="/static/virtual_try_on/garmets/tops/1.png", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 5, 9, 58, 1, 785105)
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 5, 9, 58, 1, 797608)
            ),
        ),
    ]
