# Generated by Django 5.0.1 on 2024-07-05 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0124_customuser_avatar_body_customuser_avatar_bottom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 5, 22, 44, 5, 684816)
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 5, 22, 44, 5, 684816)
            ),
        ),
    ]
