version: 2
updates:
  - package-ecosystem: "pip" # Specify the package manager, e.g., pip for Python
    directory: "/" # Location of the requirements.txt file or other manifest
    schedule:
      interval: "weekly" # Update schedule - can be daily, weekly, or monthly
  - package-ecosystem: "npm" # Specify the package manager, e.g., npm for JavaScript
    directory: "/" # Location of the package.json file
    schedule:
      interval: "weekly"
