# Date: 2024-3-1
# Author: Generated by GoCodeo.


from django.test import TestCase 

from django.urls import reverse 

from django.contrib.auth.models import User 

class TestRegisterView(unittest.TestCase):

	    def test_dashboard_view(self):
	        user = User.objects.create_user(username='testuser', password='testpassword')
	        self.client.login(username='testuser', password='testpassword')
	        response = self.client.get(reverse('journal:dashboard'))
	        self.assertEqual(response.status_code, 200)
	        self.assertTemplateUsed(response, 'dashboard.html') 


