# Date: 2024-3-1
# Author: Generated by GoCodeo.


from django.test import TestCase 

from django.urls import reverse 

from django.contrib.auth.models import User 

class TestRegisterView(unittest.TestCase):

	    def test_profile_update(self):
	        user = User.objects.create_user(username='testuser', password='testpassword')
	        self.client.login(username='testuser', password='testpassword')
	        response = self.client.post(reverse('journal:profile_update'), {'username': 'newusername', 'email': 'newemail@example.com'})
	        self.assertEqual(response.status_code, 302)
	        self.assertEqual(response.url, reverse('journal:profile'))
	        updated_user = User.objects.get(username='newusername')
	        self.assertEqual(updated_user.email, 'newemail@example.com') 


