# Date: 2024-3-1
# Author: Generated by GoCodeo.


from django.test import TestCase 

from django.urls import reverse 

from django.contrib.auth.models import User 

class TestRegisterView(unittest.TestCase):

	    def test_register_success(self):
	        response = self.client.post(reverse('register'), {
	            'username': 'testuser',
	            'password1': 'testpassword',
	            'password2': 'testpassword'
	        })
	        self.assertEqual(response.status_code, 302)
	        self.assertRedirects(response, reverse('profile_update')) 


