# Generated by Django 5.1.3 on 2024-12-05 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('body', 'Body'), ('hair', 'Hair'), ('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('makeup', 'Makeup'), ('wig', 'Wig'), ('jewellery', 'Jewellery'), ('lingerie', 'Lingerie'), ('background', 'Background')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('image_path', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('price_points', models.IntegerField(blank=True, default=0, null=True)),
                ('price_dollars', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('premium_only', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_path', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.CharField(choices=[('00', 'straight_body'), ('02', 'curvy_body'), ('03', 'hourglass_body'), ('04', 'pear_body'), ('05', 'apple_body'), ('06', 'athletic_body'), ('01', 'petite_body')], default='00', max_length=2)),
                ('skin', models.CharField(choices=[('00', 'light'), ('01', 'olive'), ('02', 'medium'), ('03', 'dark'), ('04', 'pale'), ('05', 'tan')], default='00', max_length=10)),
                ('hair', models.CharField(choices=[('00', 'short_hair'), ('02', 'long_straight_hair'), ('03', 'long_curly_hair'), ('04', 'long_wavy_hair'), ('05', 'bob_cut'), ('06', 'pig_tails'), ('07', 'bald'), ('08', 'short_curly_hair'), ('09', 'short_wavy_hair'), ('10', 'long_straight_bangs'), ('11', 'long_curly_bangs'), ('12', 'long_wavy_bangs'), ('13', 'bob_cut_bangs'), ('14', 'pig_tails_bangs'), ('15', 'short_curly_bangs'), ('01', 'short_wavy_bangs')], default='00', max_length=2)),
                ('hair_color', models.CharField(choices=[('00', 'none'), ('01', 'black'), ('02', 'brown'), ('03', 'blonde'), ('04', 'red'), ('05', 'blue'), ('06', 'green'), ('07', 'purple'), ('08', 'pink'), ('09', 'rainbow')], default='00', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('shoes', models.CharField(choices=[('00', 'ugly shoes'), ('01', 'Sneakers'), ('02', 'Boots'), ('03', 'Heels'), ('04', 'Flats'), ('05', 'Sandals'), ('06', 'Wedges'), ('07', 'Mules'), ('08', 'Pumps'), ('09', 'Platforms'), ('10', 'Ankle Boots'), ('11', 'Thigh High Boots'), ('12', 'Knee High Boots')], default='00', max_length=100)),
                ('accessories', models.CharField(choices=[('00', 'None'), ('01', 'Hat'), ('02', 'Scarf'), ('03', 'Gloves'), ('04', 'Sunglasses'), ('05', 'Handbag'), ('06', 'Necklace'), ('07', 'Bracelet'), ('08', 'Earrings'), ('09', 'collar'), ('10', 'Belt')], default='00', max_length=100)),
                ('skirt', models.CharField(choices=[('00', 'ugly shorts'), ('01', 'Mini Skirt'), ('02', 'Midi Skirt'), ('03', 'Maxi Skirt'), ('04', 'Pencil Skirt'), ('05', 'Pleated Skirt'), ('06', 'A-Line Skirt')], default='00', max_length=100)),
                ('top', models.CharField(choices=[('00', 'ugly top'), ('01', 'T-Shirt'), ('02', 'Blouse'), ('03', 'Crop Top'), ('04', 'Bra'), ('05', 'Corset'), ('06', 'Bustier')], default='00', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
                ('purchased_items', models.ManyToManyField(blank=True, to='dressup.item')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoShoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer_type', models.CharField(choices=[('creepy', 'Creepy Photographer'), ('hot', 'Hot Photographer')], max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='photoshoots/')),
                ('used', models.BooleanField(default=False)),
                ('backdrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dressup.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dressup.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(choices=[('salon', 'Salon'), ('thrift_shop', 'Thrift Shop'), ('high_end', 'High-End Department'), ('designer', 'Designer'), ('jewellery', 'Jewellery'), ('lingerie', 'Lingerie'), ('shoes', 'Shoes'), ('designer_shoes', 'Designer Shoes'), ('wig_shop', 'Wig Shop'), ('gym', 'Gym'), ('bank', 'Bank'), ('photography_studio', 'Photography Studio')], max_length=50)),
                ('premium_only', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('items', models.ManyToManyField(related_name='shops', to='dressup.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='dressup.shop'),
        ),
    ]
