# Generated by Django 5.2 on 2025-05-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Sissy Avatar", max_length=100)),
                (
                    "body",
                    models.CharField(
                        choices=[
                            ("00", "Straight"),
                            ("01", "Petite"),
                            ("02", "Curvy"),
                            ("03", "Hourglass"),
                        ],
                        default="00",
                        max_length=2,
                    ),
                ),
                (
                    "skin",
                    models.CharField(
                        choices=[("00", "Light"), ("01", "Tan"), ("02", "Dark")],
                        default="00",
                        max_length=2,
                    ),
                ),
                (
                    "hair",
                    models.CharField(
                        choices=[
                            ("00", "Short"),
                            ("01", "Wavy Bangs"),
                            ("02", "Long Straight"),
                        ],
                        default="00",
                        max_length=20,
                    ),
                ),
                (
                    "hair_color",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("brunette", "Brunette"),
                            ("blonde", "Blonde"),
                            ("red", "Red"),
                            ("pink", "Pink"),
                        ],
                        default="black",
                        max_length=20,
                    ),
                ),
                ("story_started", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("body", "Body"),
                            ("hair", "Hair"),
                            ("top", "Top"),
                            ("skirt", "Skirt"),
                            ("shoes", "Shoes"),
                            ("accessories", "Accessories"),
                            ("makeup", "Makeup"),
                            ("wig", "Wig"),
                            ("jewellery", "Jewellery"),
                            ("lingerie", "Lingerie"),
                            ("background", "Background"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image_path", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "price_points",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "price_dollars",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("premium_only", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PhotoShoot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photographer_type",
                    models.CharField(
                        choices=[
                            ("booth", "Photo Booth"),
                            ("creepy", "Creepy Photographer"),
                            ("hot", "Hot Photographer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="photoshoots/")),
                ("used", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                ("is_equipped", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("shop_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "shop_type",
                    models.CharField(
                        choices=[
                            ("salon", "Salon"),
                            ("thrift_shop", "Thrift Shop"),
                            ("high_end", "High-End Department"),
                            ("designer", "Designer"),
                            ("jewellery", "Jewellery"),
                            ("lingerie", "Lingerie"),
                            ("shoes", "Shoes"),
                            ("designer_shoes", "Designer Shoes"),
                            ("wig_shop", "Wig Shop"),
                            ("gym", "Gym"),
                            ("bank", "Bank"),
                            ("photography_studio", "Photography Studio"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "shop_level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("premium", "Premium"),
                            ("cute", "Cute"),
                            ("hawt", "Hawt"),
                            ("sexy", "Sexy"),
                        ],
                        default="basic",
                        max_length=50,
                    ),
                ),
                ("premium_only", models.BooleanField(default=False)),
                ("is_locked", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("image_path", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
