# Generated by Django 5.1.3 on 2024-12-02 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('body', 'Body'), ('hair', 'Hair'), ('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('makeup', 'Makeup'), ('wig', 'Wig'), ('jewellery', 'Jewellery'), ('lingerie', 'Lingerie'), ('background', 'Background')], max_length=50)),
                ('image', models.ImageField(upload_to='items/')),
                ('price_points', models.PositiveIntegerField(blank=True, null=True)),
                ('price_dollars', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('premium_only', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shop_type', models.CharField(choices=[('salon', 'Salon'), ('thrift_shop', 'Thrift Shop'), ('high_end', 'High-End Department'), ('designer', 'Designer'), ('jewellery', 'Jewellery'), ('lingerie', 'Lingerie'), ('shoes', 'Shoes'), ('designer_shoes', 'Designer Shoes'), ('wig_shop', 'Wig Shop'), ('gym', 'Gym'), ('bank', 'Bank'), ('photography_studio', 'Photography Studio')], max_length=50)),
                ('premium_only', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('things', models.ManyToManyField(related_name='shops', to='dressup.thing')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_things', to=settings.AUTH_USER_MODEL)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dressup.thing')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoShoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer_type', models.CharField(choices=[('creepy', 'Creepy Photographer'), ('hot', 'Hot Photographer')], max_length=20)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='photoshoots/')),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('backdrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dressup.thing')),
            ],
        ),
    ]
    