# Generated by Django 5.1.2 on 2025-04-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dressup", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="hair_color",
            field=models.CharField(
                choices=[
                    ("00", "Black"),
                    ("01", "Brunette"),
                    ("02", "Blonde"),
                    ("03", "Red"),
                    ("04", "Pink"),
                ],
                default="00",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("body", "Body"),
                    ("hair", "Hair"),
                    ("top", "Top"),
                    ("skirt", "Skirt"),
                    ("shoes", "Shoes"),
                    ("accessory", "Accessory"),
                    ("makeup", "Makeup"),
                    ("wig", "Wig"),
                    ("jewellery", "Jewellery"),
                    ("lingerie", "Lingerie"),
                    ("background", "Background"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="LeaderboardEntry",
        ),
    ]
