# Generated by Django 5.1.3 on 2024-12-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='accessories',
            field=models.CharField(choices=[('00', 'None'), ('01', 'Hat'), ('02', 'Scarf'), ('03', 'Gloves'), ('04', 'Sunglasses'), ('05', 'Handbag'), ('06', 'Necklace'), ('07', 'Bracelet'), ('08', 'Earrings'), ('09', 'Collar'), ('10', 'Belt')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='body',
            field=models.CharField(choices=[('00', 'straight_body'), ('01', 'petite_body'), ('02', 'curvy_body'), ('03', 'hourglass_body'), ('04', 'pear_body'), ('05', 'apple_body'), ('06', 'athletic_body')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='hair',
            field=models.CharField(choices=[('00', 'short_hair'), ('01', 'short_wavy_bangs'), ('02', 'long_straight_hair'), ('03', 'long_curly_hair'), ('04', 'long_wavy_hair'), ('05', 'bob_cut'), ('06', 'pig_tails'), ('07', 'bald'), ('08', 'short_curly_hair'), ('09', 'short_wavy_hair'), ('10', 'long_straight_bangs'), ('11', 'long_curly_bangs'), ('12', 'long_wavy_bangs'), ('13', 'bob_cut_bangs'), ('14', 'pig_tails_bangs'), ('15', 'short_curly_bangs')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='hair_color',
            field=models.CharField(choices=[('00', 'none'), ('01', 'black'), ('02', 'brown'), ('03', 'blonde'), ('04', 'red'), ('05', 'blue'), ('06', 'green'), ('07', 'purple'), ('08', 'pink'), ('09', 'rainbow')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='shoes',
            field=models.CharField(choices=[('00', 'Basic Shoes'), ('01', 'Sneakers'), ('02', 'Boots'), ('03', 'Heels'), ('04', 'Flats'), ('05', 'Sandals'), ('06', 'Wedges'), ('07', 'Mules'), ('08', 'Pumps'), ('09', 'Platforms'), ('10', 'Ankle Boots'), ('11', 'Thigh High Boots'), ('12', 'Knee High Boots')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='skin',
            field=models.CharField(choices=[('00', 'light'), ('01', 'olive'), ('02', 'medium'), ('03', 'dark'), ('04', 'pale'), ('05', 'tan')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='skirt',
            field=models.CharField(choices=[('00', 'Basic Shorts'), ('01', 'Mini Skirt'), ('02', 'Midi Skirt'), ('03', 'Maxi Skirt'), ('04', 'Pencil Skirt'), ('05', 'Pleated Skirt'), ('06', 'A-Line Skirt')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='top',
            field=models.CharField(choices=[('00', 'Basic Top'), ('01', 'T-Shirt'), ('02', 'Blouse'), ('03', 'Crop Top'), ('04', 'Bra'), ('05', 'Corset'), ('06', 'Bustier')], default='00', max_length=2),
        ),
    ]
