# Generated by Django 5.0.1 on 2024-07-27 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dressup", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("top", "Top"),
                            ("bottom", "Bottom"),
                            ("shoes", "Shoes"),
                            ("accessories", "Accessories"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image", models.ImageField(upload_to="items/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("premium", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dressup.item"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="avatar",
            name="top",
            field=models.CharField(default="default_top", max_length=255),
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="dress",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="skirt",
        ),
        migrations.AlterField(
            model_name="avatar",
            name="shoes",
            field=models.CharField(default="default_shoes", max_length=255),
        ),
        migrations.DeleteModel(
            name="Environment",
        ),
        migrations.RemoveField(
            model_name="favorites",
            name="outfit",
        ),
        migrations.RemoveField(
            model_name="favorites",
            name="user",
        ),
        migrations.DeleteModel(
            name="Feature",
        ),
        migrations.DeleteModel(
            name="Pose",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="body_type",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="hair_color",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="hair_type",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="skin_tone",
        ),
        migrations.AddField(
            model_name="avatar",
            name="accessories",
            field=models.CharField(default="default_accessories", max_length=255),
        ),
        migrations.AddField(
            model_name="avatar",
            name="body",
            field=models.CharField(default="default_body", max_length=255),
        ),
        migrations.AddField(
            model_name="avatar",
            name="bottom",
            field=models.CharField(default="default_bottom", max_length=255),
        ),
        migrations.AddField(
            model_name="avatar",
            name="eyes",
            field=models.CharField(default="default_eyes", max_length=255),
        ),
        migrations.AddField(
            model_name="avatar",
            name="hair",
            field=models.CharField(default="default_hair", max_length=255),
        ),
        migrations.DeleteModel(
            name="ClothingItem",
        ),
        migrations.DeleteModel(
            name="PremiumOutfit",
        ),
        migrations.DeleteModel(
            name="Favorites",
        ),
    ]
