# Generated by Django 5.2.4 on 2025-07-16 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dressup", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sissy_avatar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="avatar",
            name="equipped_item",
            field=models.ManyToManyField(
                blank=True, related_name="item", to="dressup.item"
            ),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="photoshoot",
            name="backdrop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dressup.item"
            ),
        ),
        migrations.AddField(
            model_name="photoshoot",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="purchaseditem",
            name="avatar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_item",
                to="dressup.avatar",
            ),
        ),
        migrations.AddField(
            model_name="purchaseditem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dressup.item"
            ),
        ),
        migrations.AddField(
            model_name="savedoutfit",
            name="avatar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_outfit",
                to="dressup.avatar",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="item",
            field=models.ManyToManyField(related_name="shop_item", to="dressup.item"),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseditem",
            unique_together={("avatar", "item")},
        ),
    ]
