# Generated by Django 5.1.2 on 2025-01-30 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dressup", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sissy_avatar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="avatar",
            name="purchased_items",
            field=models.ManyToManyField(blank=True, to="dressup.item"),
        ),
        migrations.AddField(
            model_name="leaderboardentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="photoshoot",
            name="backdrop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dressup.item"
            ),
        ),
        migrations.AddField(
            model_name="photoshoot",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="purchaseditem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dressup.item"
            ),
        ),
        migrations.AddField(
            model_name="purchaseditem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="items",
            field=models.ManyToManyField(related_name="shop_items", to="dressup.item"),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseditem",
            unique_together={("user", "item")},
        ),
    ]
