# Generated by Django 5.1.3 on 2024-12-03 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.CharField(choices=[('01', 'straight_body'), ('02', 'curvy_body'), ('03', 'hourglass_body'), ('04', 'pear_body'), ('05', 'apple_body'), ('06', 'athletic_body'), ('07', 'petite_body')], default='01', max_length=2)),
                ('skin', models.CharField(choices=[('01', 'light'), ('02', 'medium'), ('03', 'dark'), ('04', 'pale'), ('05', 'tan')], default='light', max_length=10)),
                ('hair', models.CharField(choices=[('01', 'short_hair'), ('02', 'long_straight_hair'), ('03', 'long_curly_hair'), ('04', 'long_wavy_hair'), ('05', 'bob_cut'), ('06', 'pig_tails'), ('07', 'bald'), ('08', 'short_curly_hair'), ('09', 'short_wavy_hair'), ('10', 'long_straight_bangs'), ('11', 'long_curly_bangs'), ('12', 'long_wavy_bangs'), ('13', 'bob_cut_bangs'), ('14', 'pig_tails_bangs'), ('15', 'short_curly_bangs'), ('16', 'short_wavy_bangs')], default='01', max_length=2)),
                ('hair_color', models.CharField(choices=[('01', 'black'), ('02', 'brown'), ('03', 'blonde'), ('04', 'red'), ('05', 'blue'), ('06', 'green'), ('07', 'purple'), ('08', 'pink'), ('09', 'rainbow')], default='black', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('purchased_things', models.ManyToManyField(blank=True, to='dressup.thing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
