# Generated by Django 5.1.2 on 2025-01-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dressup", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="equipped_items",
            field=models.ManyToManyField(
                blank=True, related_name="equipped_items", to="dressup.item"
            ),
        ),
    ]
