# Generated by Django 5.1.3 on 2024-12-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0002_alter_avatar_accessories_alter_avatar_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='hair',
            field=models.CharField(choices=[('00', 'short_hair'), ('01', 'short_wavy_bangs'), ('02', 'long_straight_hair'), ('03', 'long_curly_hair'), ('04', 'long_wavy_hair'), ('05', 'bob_cut'), ('06', 'pig_tails'), ('07', 'bald'), ('08', 'short_curly_hair'), ('09', 'short_wavy_hair'), ('10', 'long_straight_bangs'), ('11', 'long_curly_bangs'), ('12', 'long_wavy_bangs'), ('13', 'bob_cut_bangs'), ('14', 'pig_tails_bangs'), ('15', 'short_curly_bangs')], default='00', max_length=20),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='hair_color',
            field=models.CharField(choices=[('00', 'none'), ('black', 'black'), ('brunette', 'brown'), ('blonde', 'blonde'), ('red', 'red'), ('05', 'blue'), ('06', 'green'), ('07', 'purple'), ('pink', 'pink'), ('09', 'rainbow')], default='00', max_length=20),
        ),
        migrations.AlterField(
            model_name='photoshoot',
            name='photographer_type',
            field=models.CharField(choices=[('booth', 'Photo Booth'), ('creepy', 'Creepy Photographer'), ('hot', 'Hot Photographer')], max_length=20),
        ),
    ]
