# Generated by Django 5.2.3 on 2025-06-23 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dressup", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="hair",
            field=models.CharField(
                choices=[
                    ("00", "Short"),
                    ("01", "Wavy Bangs"),
                    ("02", "Long Straight"),
                ],
                default="00",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="SavedOutfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("top", models.CharField(max_length=20)),
                ("skirt", models.CharField(max_length=20)),
                ("shoes", models.CharField(max_length=20)),
                ("accessory", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
