# Generated by Django 5.1.3 on 2024-12-03 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0002_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('body', 'Body'), ('hair', 'Hair'), ('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('makeup', 'Makeup'), ('wig', 'Wig'), ('jewellery', 'Jewellery'), ('lingerie', 'Lingerie'), ('background', 'Background')], max_length=50)),
                ('image', models.ImageField(upload_to='items/')),
                ('price_points', models.PositiveIntegerField(blank=True, null=True)),
                ('price_dollars', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('premium_only', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ]
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dressup.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
