# Generated by Django 5.2.3 on 2025-06-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dressup", "0003_alter_avatar_hair_savedoutfit"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="outfit_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
