# Generated by Django 5.1.3 on 2024-12-03 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0003_rename_purchased_things_avatar_purchased_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='accessories',
            field=models.CharField(choices=[('00', 'None'), ('01', 'Hat'), ('02', 'Scarf'), ('03', 'Gloves'), ('04', 'Sunglasses'), ('05', 'Handbag'), ('06', 'Necklace'), ('07', 'Bracelet'), ('08', 'Earrings'), ('09', 'collar'), ('10', 'Belt')], default='00', max_length=100),
        ),
        migrations.AddField(
            model_name='avatar',
            name='image_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='purchased_items',
            field=models.ManyToManyField(blank=True, to='dressup.item'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='shoes',
            field=models.CharField(choices=[('00', 'ugly shoes'), ('01', 'Sneakers'), ('02', 'Boots'), ('03', 'Heels'), ('04', 'Flats'), ('05', 'Sandals'), ('06', 'Wedges'), ('07', 'Mules'), ('08', 'Pumps'), ('09', 'Platforms'), ('10', 'Ankle Boots'), ('11', 'Thigh High Boots'), ('12', 'Knee High Boots')], default='00', max_length=100),
        ),
        migrations.AddField(
            model_name='avatar',
            name='skirt',
            field=models.CharField(choices=[('00', 'ugly shorts'), ('01', 'Mini Skirt'), ('02', 'Midi Skirt'), ('03', 'Maxi Skirt'), ('04', 'Pencil Skirt'), ('05', 'Pleated Skirt'), ('06', 'A-Line Skirt')], default='00', max_length=100),
        ),
        migrations.AddField(
            model_name='avatar',
            name='top',
            field=models.CharField(choices=[('00', 'ugly top'), ('01', 'T-Shirt'), ('02', 'Blouse'), ('03', 'Crop Top'), ('04', 'Bra'), ('05', 'Corset'), ('06', 'Bustier')], default='00', max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='items',
            field=models.ManyToManyField(related_name='shops', to='dressup.item'),
        ),
    ]
