# Generated by Django 5.0.1 on 2024-08-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dressup", "0003_alter_avatar_accessories_alter_avatar_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
