# Generated by Django 5.1.2 on 2025-02-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dressup", "0004_remove_avatar_created_at_remove_avatar_image_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avatar",
            name="accessories",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="shoes",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="skirt",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="story_started",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="top",
        ),
        migrations.AddField(
            model_name="avatar",
            name="name",
            field=models.CharField(default="Sissy Avatar", max_length=100),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="body",
            field=models.CharField(
                choices=[
                    ("00", "straight_body"),
                    ("01", "petite_body"),
                    ("02", "curvy_body"),
                    ("03", "hourglass_body"),
                ],
                default="00",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="equipped_items",
            field=models.ManyToManyField(
                blank=True,
                help_text="Items currently equipped on the avatar.",
                related_name="equipped_on_avatars",
                to="dressup.item",
            ),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="hair",
            field=models.CharField(
                choices=[
                    ("00", "short_hair"),
                    ("01", "short_wavy_bangs"),
                    ("02", "long_straight_hair"),
                ],
                default="00",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="hair_color",
            field=models.CharField(
                choices=[
                    ("black", "Black"),
                    ("brunette", "Brunette"),
                    ("blonde", "Blonde"),
                    ("red", "Red"),
                    ("pink", "Pink"),
                ],
                default="black",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="skin",
            field=models.CharField(
                choices=[("00", "light"), ("01", "tan"), ("02", "dark")],
                default="00",
                max_length=2,
            ),
        ),
    ]
