# Generated by Django 5.1.3 on 2024-12-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0005_remove_item_image_remove_shop_image_item_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='equipped_items',
            field=models.ManyToManyField(blank=True, help_text='Items currently equipped on the avatar.', related_name='equipped_on_avatars', to='dressup.item'),
        ),
    ]
