# Generated by Django 5.1.2 on 2025-02-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dressup", "0006_avatar_story_started"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="hair_color",
            field=models.CharField(
                choices=[
                    ("00", "Black"),
                    ("01", "Brunette"),
                    ("02", "Blonde"),
                    ("03", "Red"),
                    ("04", "Pink"),
                ],
                default="00",
                max_length=20,
            ),
        ),
    ]
