# Generated by Django 5.0.1 on 2024-10-01 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dressup", "0006_alter_avatar_accessories_alter_avatar_body_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClothingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TOP", "Top"),
                            ("BOTTOM", "Bottom"),
                            ("DRESS", "Dress"),
                            ("SHOES", "Shoes"),
                            ("ACCESSORY", "Accessory"),
                        ],
                        max_length=10,
                    ),
                ),
                ("image", models.ImageField(upload_to="clothing_items/")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_premium", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PhotoshootLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="photoshoot_locations/")),
                ("is_premium", models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name="item",
            old_name="premium",
            new_name="is_premium",
        ),
        migrations.AddField(
            model_name="avatar",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="accessories",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/accessories/"
            ),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="bottom",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/bottom/"),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="shoes",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/shoes/"),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="top",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/top/"),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avatar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("TOP", "Top"),
                    ("BOTTOM", "Bottom"),
                    ("SHOES", "Shoes"),
                    ("ACCESSORY", "Accessories"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseditem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchased_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FavoriteOutfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("outfit_name", models.CharField(max_length=100)),
                ("clothing_items", models.ManyToManyField(to="dressup.clothingitem")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_outfits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
