# Generated by Django 5.1.3 on 2024-12-10 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0007_remove_item_shop_item_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='hair_color',
            field=models.CharField(choices=[('00', 'none'), ('black', 'black'), ('brunette', 'brown'), ('blonde', 'blonde'), ('red', 'red'), ('pink', 'pink')], default='00', max_length=20),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sissy_avatar', to=settings.AUTH_USER_MODEL),
        ),
    ]
