# Generated by Django 5.0.1 on 2024-10-03 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dressup", "0008_remove_favoriteoutfit_clothing_items_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("top", "Top"),
                    ("bottom", "Bottom"),
                    ("shoes", "Shoes"),
                    ("accessories", "Accessories"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseditem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="ClothingItem",
        ),
        migrations.DeleteModel(
            name="FavoriteOutfit",
        ),
    ]
