# Generated by Django 5.1.3 on 2024-12-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0008_alter_avatar_hair_color_alter_avatar_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_id',
            field=models.CharField(default='shop', max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='items',
            field=models.ManyToManyField(related_name='shop_items', to='dressup.item'),
        ),
    ]
