# Generated by Django 5.1.3 on 2024-12-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0009_shop_shop_id_alter_shop_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
