# Generated by Django 5.1.3 on 2024-12-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0010_alter_shop_shop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='purchased_items',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='accessories',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='body',
            field=models.CharField(choices=[('00', 'straight_body'), ('01', 'petite_body'), ('02', 'curvy_body')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='hair',
            field=models.CharField(choices=[('00', 'short_hair'), ('01', 'short_wavy_bangs'), ('02', 'long_straight_hair')], default='00', max_length=20),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='hair_color',
            field=models.CharField(choices=[('00', 'none'), ('black', 'black')], default='00', max_length=20),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='shoes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='skin',
            field=models.CharField(choices=[('00', 'light'), ('01', 'olive'), ('02', 'medium'), ('03', 'dark')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='skirt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='top',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
