# Generated by Django 5.1.3 on 2024-12-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0011_remove_avatar_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='shoes',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='skirt',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='top',
        ),
        migrations.AddField(
            model_name='avatar',
            name='accessories_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='shoes_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='skirt_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='top_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='hair_color',
            field=models.CharField(choices=[('00', 'black'), ('01', 'brown'), ('02', 'blonde'), ('03', 'red'), ('04', 'purple'), ('05', 'green'), ('06', 'blue'), ('07', 'pink'), ('08', 'orange'), ('09', 'white')], default='00', max_length=20),
        ),
    ]
