# Generated by Django 5.1.3 on 2024-12-13 13:23

from django.db import migrations
from django.db import migrations


def transfer_equipped_items(apps, schema_editor):
    Avatar = apps.get_model('dressup', 'Avatar')
    Item = apps.get_model('dressup', 'Item')

    for avatar in Avatar.objects.all():
        equipped_items = []
        for category in ['shoes', 'accessories', 'skirt', 'top']:
            item_id = getattr(avatar, f'{category}_id', None)
            if item_id:
                try:
                    item = Item.objects.get(id=item_id)
                    equipped_items.append(item)
                except Item.DoesNotExist:
                    pass

        # Add items to equipped_items
        avatar.equipped_items.set(equipped_items)
        avatar.save()


class Migration(migrations.Migration):
    dependencies = [
        ('dressup', '0012_remove_avatar_accessories_remove_avatar_created_at_and_more'),
    ]


    operations = [
        migrations.RunPython(transfer_equipped_items),

        migrations.RemoveField(
            model_name='avatar',
            name='accessories_id',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='shoes_id',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='skirt_id',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='top_id',
        ),
    ]
