# Generated by Django 5.1.3 on 2024-12-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0013_remove_avatar_accessories_id_remove_avatar_shoes_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='body',
            field=models.CharField(choices=[('00', 'straight_body'), ('01', 'petite_body'), ('02', 'curvy_body'), ('03', 'hourglass_body')], default='00', max_length=2),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='hair_color',
            field=models.CharField(choices=[('black', 'black'), ('brunette', 'brunette'), ('blonde', 'blonde'), ('red', 'red'), ('pink', 'pink')], default='00', max_length=20),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='skin',
            field=models.CharField(choices=[('00', 'light'), ('01', 'tan'), ('02', 'dark')], default='00', max_length=2),
        ),
    ]
