# Generated by Django 5.1.3 on 2024-12-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0014_alter_avatar_body_alter_avatar_hair_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='hair_color',
            field=models.CharField(choices=[('black', 'black'), ('brunette', 'brunette'), ('blonde', 'blonde'), ('red', 'red'), ('pink', 'pink')], default='black', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('body', 'Body'), ('hair', 'Hair'), ('top', 'Tops'), ('skirt', 'Skirts'), ('shoes', 'Shoes'), ('accessory', 'Accessories'), ('makeup', 'Makeup'), ('wig', 'Wigs'), ('jewellery', 'Jewellery'), ('lingerie', 'Lingerie'), ('background', 'Backgrounds')], max_length=50),
        ),
    ]
