# Generated by Django 5.1.3 on 2024-12-23 20:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0015_alter_avatar_hair_color_alter_item_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseditem',
            unique_together={('user', 'item')},
        ),
    ]
