# Generated by Django 5.1.3 on 2025-01-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0017_remove_photoshoot_backdrop_remove_photoshoot_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='hair',
            field=models.CharField(choices=[('h1', 'Short'), ('h2', 'Wavy'), ('h3', 'Long'), ('h4', 'Bald'), ('h5', 'Curly')], default='00', max_length=20),
        ),
    ]
