# Generated by Django 5.1.3 on 2025-01-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dressup', '0018_alter_avatar_hair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='skin',
            field=models.CharField(choices=[('00', 'Light'), ('01', 'Tan'), ('02', 'Dark'), ('03', 'Ebony'), ('04', 'Albino'), ('05', 'Olive')], default='00', max_length=2),
        ),
    ]
