# Generated by Django 5.0.1 on 2024-06-17 05:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_try_on", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumOutfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="premium_outfits/")),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserAvatar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skin_tone",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("dark", "Dark"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "hair_style",
                    models.CharField(
                        choices=[
                            ("short", "Short"),
                            ("long", "Long"),
                            ("curly", "Curly"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserOutfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "outfit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtual_try_on.premiumoutfit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="outfit",
            name="clothing_items",
        ),
        migrations.RemoveField(
            model_name="outfit",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserImage",
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="favorites",
            name="clothing_items",
            field=models.ManyToManyField(blank=True, to="virtual_try_on.clothingitem"),
        ),
        migrations.AlterField(
            model_name="favorites",
            name="outfits",
            field=models.ManyToManyField(blank=True, to="virtual_try_on.premiumoutfit"),
        ),
        migrations.DeleteModel(
            name="Outfit",
        ),
    ]
