# Generated by Django 5.0.1 on 2024-06-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "virtual_try_on",
            "0003_avatar_garmentcategory_remove_clothingitem_category_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="environments/")),
            ],
        ),
        migrations.CreateModel(
            name="Outfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="outfits/")),
            ],
        ),
        migrations.CreateModel(
            name="Pose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("standing", "Standing"),
                            ("sitting_lady", "Sitting ladylike"),
                            ("sitting_legspread", "Sitting slutspread"),
                            ("lying_facedown", "Lying ass up"),
                            ("kneeling", "On knees"),
                            ("dancing", "Dancing"),
                        ],
                        max_length=100,
                    ),
                ),
                ("image", models.ImageField(upload_to="poses/")),
            ],
        ),
        migrations.AddField(
            model_name="avatar",
            name="user_upload",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/user_uploads/"
            ),
        ),
    ]
