# Generated by Django 5.0.1 on 2024-06-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_try_on", "0004_environment_outfit_pose_avatar_user_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="premiumoutfit",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10
            ),
            preserve_default=False,
        ),
    ]
