# Generated by Django 5.0.1 on 2024-06-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_try_on", "0005_premiumoutfit_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="premiumoutfit",
            options={
                "ordering": ["name"],
                "verbose_name": "Premium Outfit",
                "verbose_name_plural": "Premium Outfits",
            },
        ),
        migrations.AlterField(
            model_name="premiumoutfit",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
