# Generated by Django 5.0.1 on 2024-06-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_try_on", "0006_alter_premiumoutfit_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="premiumoutfit",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
