# Generated by Django 5.0.1 on 2024-06-23 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_try_on", "0007_alter_premiumoutfit_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name="clothingitem",
            name="user",
        ),
        migrations.RemoveField(
            model_name="garment",
            name="category",
        ),
        migrations.DeleteModel(
            name="Outfit",
        ),
        migrations.RemoveField(
            model_name="useravatar",
            name="user",
        ),
        migrations.RemoveField(
            model_name="useroutfit",
            name="outfit",
        ),
        migrations.RemoveField(
            model_name="useroutfit",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usertryonresult",
            name="user",
        ),
        migrations.RenameField(
            model_name="avatar",
            old_name="name",
            new_name="outfit",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="image",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="user_upload",
        ),
        migrations.AddField(
            model_name="avatar",
            name="accessories",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="avatar",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("hourglass", "Hourglass"),
                    ("pear", "Pear"),
                    ("apple", "Apple"),
                    ("rectangle", "Rectangle"),
                    ("inverted_triangle", "Inverted Triangle"),
                ],
                default="hourglass",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="avatar",
            name="hair_color",
            field=models.CharField(
                choices=[
                    ("black", "Black"),
                    ("brown", "Brown"),
                    ("blonde", "Blonde"),
                    ("red", "Red"),
                    ("gray", "Gray"),
                ],
                default="black",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="avatar",
            name="hair_style",
            field=models.CharField(
                choices=[
                    ("long_straight", "Long Straight"),
                    ("long_curly", "Long Curly"),
                    ("short_straight", "Short Straight"),
                    ("short_curly", "Short Curly"),
                    ("bald", "Bald"),
                ],
                default="long_straight",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="avatar",
            name="skin_tone",
            field=models.CharField(
                choices=[("light", "Light"), ("medium", "Medium"), ("dark", "Dark")],
                default="light",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="avatar",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ClothingItem",
        ),
        migrations.DeleteModel(
            name="Garment",
        ),
        migrations.DeleteModel(
            name="GarmentCategory",
        ),
        migrations.DeleteModel(
            name="UserAvatar",
        ),
        migrations.DeleteModel(
            name="UserOutfit",
        ),
        migrations.DeleteModel(
            name="UserTryOnResult",
        ),
    ]
