# Generated by Django 5.0.1 on 2024-06-23 05:51

import django.db.models.deletion
import virtual_try_on.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_try_on", "0008_feature_remove_clothingitem_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="user",
            field=models.ForeignKey(
                default=virtual_try_on.models.get_default_user,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
