# Generated by Django 5.0.1 on 2024-06-23 11:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_try_on", "0009_alter_avatar_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="premiumoutfit",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=4
            ),
        ),
    ]
