# Generated by Django 5.0.1 on 2024-06-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_try_on", "0011_alter_avatar_body_type_alter_avatar_skin_tone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="hair_color",
            field=models.CharField(
                choices=[
                    ("black", "Black"),
                    ("brown", "Brunette"),
                    ("blonde", "Blonde"),
                    ("red", "Red"),
                    ("pink", "Pink"),
                ],
                default="black",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="hair_style",
            field=models.CharField(
                choices=[
                    ("long_straight", "Long Straight"),
                    ("long_curly", "Long Curly"),
                    ("short_straight", "Short Straight"),
                    ("short_curly", "Short Curly"),
                    ("bob", "Bobcut"),
                ],
                default="long_straight",
                max_length=50,
            ),
        ),
    ]
