# Generated by Django 5.0.1 on 2024-06-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_try_on", "0012_alter_avatar_hair_color_alter_avatar_hair_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="accessories",
            field=models.TextField(blank=True, default="none"),
        ),
        migrations.AlterField(
            model_name="premiumoutfit",
            name="description",
            field=models.TextField(blank=True, default="none"),
        ),
    ]
