# Generated by Django 5.0.1 on 2024-06-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_try_on", "0013_alter_avatar_accessories_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="avatar",
            old_name="hair_style",
            new_name="hair_type",
        ),
        migrations.AlterField(
            model_name="avatar",
            name="outfit",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
