# Generated by Django 5.0.1 on 2024-07-10 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_try_on", "0015_clothingitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avatar",
            name="accessories",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="outfit",
        ),
        migrations.AddField(
            model_name="avatar",
            name="avatar_bottom",
            field=models.CharField(
                default="/static/virtual_try_on/garmets/skirts/1.png", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="avatar",
            name="avatar_shoes",
            field=models.CharField(
                default="/static/virtual_try_on/garmets/shoes/1.png", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="avatar",
            name="avatar_top",
            field=models.CharField(
                default="/static/virtual_try_on/garmets/tops/1.png", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="body_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="hair_color",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="hair_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="skin_tone",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="avatar",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
