# Generated by Django 5.0.1 on 2024-07-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "virtual_try_on",
            "0016_remove_avatar_accessories_remove_avatar_outfit_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="clothingitem",
            old_name="owned",
            new_name="is_premium",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="avatar_bottom",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="avatar_shoes",
        ),
        migrations.RemoveField(
            model_name="avatar",
            name="avatar_top",
        ),
        migrations.RemoveField(
            model_name="clothingitem",
            name="image",
        ),
        migrations.RemoveField(
            model_name="clothingitem",
            name="user",
        ),
        migrations.AddField(
            model_name="avatar",
            name="dress",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avatar_dress",
                to="virtual_try_on.clothingitem",
            ),
        ),
        migrations.AddField(
            model_name="avatar",
            name="shoes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avatar_shoes",
                to="virtual_try_on.clothingitem",
            ),
        ),
        migrations.AddField(
            model_name="avatar",
            name="skirt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avatar_skirt",
                to="virtual_try_on.clothingitem",
            ),
        ),
        migrations.AddField(
            model_name="avatar",
            name="top",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="avatar_top",
                to="virtual_try_on.clothingitem",
            ),
        ),
        migrations.AddField(
            model_name="clothingitem",
            name="image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="clothingitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("top", "Top"),
                    ("skirt", "Skirt"),
                    ("dress", "Dress"),
                    ("shoes", "Shoes"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="clothingitem",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
