# Generated by Django 5.0.1 on 2024-07-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("virtual_try_on", "0017_rename_owned_clothingitem_is_premium_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothingitem",
            name="image_url",
            field=models.CharField(max_length=255),
        ),
    ]
